version: "3.8"

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: corpus-dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    restart: always

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    restart: always
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=8001
      - AWS_REGION=${AWS_REGION:-eu-north-1}
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
    ports:
      - "8080:8080"
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV:-production}

  website:
    build:
      context: .
      dockerfile: docker/Dockerfile.website
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}

  docs:
    build:
      context: .
      dockerfile: docker/Dockerfile.docs
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}

  proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile.proxy
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - BACKEND_HOST=backend
      - BACKEND_PORT=8001
      - DASHBOARD_HOST=dashboard
      - DASHBOARD_PORT=8080
      - WEBSITE_HOST=website
      - WEBSITE_PORT=3000
      - DOCS_HOST=docs
      - DOCS_PORT=3001
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - dashboard
      - website
      - docs
