FROM node:20-slim AS base

RUN npm --global install pnpm

FROM base AS pruner
RUN npm --global install turbo
WORKDIR /app
COPY . .
RUN turbo prune --scope=chat_service --docker

FROM base AS builder
ARG RAILWAY_ENVIRONMENT_NAME=production
WORKDIR /app
COPY .gitignore .gitignore
COPY .npmrc ./
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install

COPY --from=pruner /app/out/full/ .
COPY turbo.json turbo.json

RUN echo "RAILWAY_ENVIRONMENT_NAME: $RAILWAY_ENVIRONMENT_NAME"

RUN if [ "$RAILWAY_ENVIRONMENT_NAME" = "staging" ]; then \
  cp apps/chat_service/.env.staging apps/chat_service/.env.production; \
  fi

RUN NODE_OPTIONS="--max_old_space_size=4096" pnpm turbo run build --filter=chat_service...

FROM base AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nodeuser

# 🔧 Fix: Create .local and give access
RUN mkdir -p /app/.local/share/pnpm/.tools && \
    chown -R 1001:1001 /app/.local

COPY --from=builder /app .

USER nodeuser

EXPOSE 8002
CMD ["pnpm", "turbo", "run", "start", "--filter=chat_service"]
