FROM node:20-slim AS base

RUN npm --global install pnpm

FROM base AS pruner
RUN npm --global install turbo
WORKDIR /app
COPY . .
RUN turbo prune --scope=docs --docker

FROM base AS builder
ARG RAILWAY_ENVIRONMENT_NAME=production
WORKDIR /app
COPY .gitignore .gitignore
COPY .npmrc ./
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install

COPY --from=pruner /app/out/full/ .
COPY turbo.json turbo.json

ENV NEXT_TELEMETRY_DISABLED 1

RUN echo "RAILWAY_ENVIRONMENT_NAME: $RAILWAY_ENVIRONMENT_NAME"

RUN if [ "$RAILWAY_ENVIRONMENT_NAME" = "staging" ]; then \
  rm -f apps/docs/.env.production; \
  cp apps/docs/.env.staging apps/docs/.env.production; \
  NODE_OPTIONS="--max_old_space_size=4096" pnpm turbo run build --filter=docs...; \
  else \
  NODE_OPTIONS="--max_old_space_size=4096" pnpm turbo run build --filter=docs...; \
  fi

FROM base AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=builder --chown=nextjs:nodejs /app/apps/docs/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/docs/.next/static ./apps/docs/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/docs/public ./apps/docs/public

EXPOSE 3001

CMD node apps/docs/server.js