FROM node:20-slim AS base

RUN npm --global install pnpm

FROM base AS pruner
RUN npm --global install turbo
WORKDIR /app
COPY . .
RUN turbo prune --scope=website --docker

FROM base AS builder
ARG RAILWAY_ENVIRONMENT_NAME=production
WORKDIR /app
COPY .gitignore .gitignore
COPY .npmrc ./
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install

COPY --from=pruner /app/out/full/ .
COPY turbo.json turbo.json

ENV NEXT_TELEMETRY_DISABLED 1

RUN echo "RAILWAY_ENVIRONMENT_NAME: $RAILWAY_ENVIRONMENT_NAME"

RUN if [ "$RAILWAY_ENVIRONMENT_NAME" = "staging" ]; then \
  rm -f apps/website/.env.production; \
  cp apps/website/.env.staging apps/website/.env.production; \
  NODE_OPTIONS="--max_old_space_size=4096" pnpm turbo run build --filter=website...; \
  else \
  NODE_OPTIONS="--max_old_space_size=4096" pnpm turbo run build --filter=website...; \
  fi

FROM base AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=builder --chown=nextjs:nodejs /app/apps/website/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/website/.next/static ./apps/website/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/website/public ./apps/website/public

EXPOSE 3000

CMD node apps/website/server.js