import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Footer from '@/app/components/footer';
import Link from 'next/link';
import { Inter } from "next/font/google";
import Navbar from "@/app/components/navbar";



export const metadata: Metadata = {
  title: "Corpus Ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
      <html lang="en">
       
            
              <main className="flex-1 flex">
              {children}
              </main>
       
  </html>
  );
}
