import type { Metadata } from "next";

import "@/app/globals.css";
import Footer from '@/app/components/footer';
import Link from 'next/link';
import { Inter } from "next/font/google";
import Navbar from "@/app/components/navbar";



export const metadata: Metadata = {
  title: "Corpus Ai",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <>
    <html lang="en">
      <body
        className={`${inter.className} font-sans `}
      >
        <>
        <div className=" lg:block absolute top-40 left-10 -translate-y-1/2 -z-10 pointer-events-none">
        <div className="blob bg-[#FCA4FF] opacity-[40%] blur-2xl rounded-full w-[470px] h-[500px]"></div>
      </div>
      <div className=" lg:block absolute top-0 left-[40%] -translate-y-1/2 -z-10 pointer-events-none">
        <div className="blob2 bg-[#CE89FC] opacity-[40%] blur-2xl rounded-full w-[600px] h-[400px]"></div>
      </div>
       <div className=" lg:block absolute top-0 right-0 -translate-y-1/2 -z-10 pointer-events-none">
        <div className="blob bg-[#FFAAF9] opacity-[40%] blur-2xl rounded-full w-[300px] h-[300px]"></div>
      </div>
      <div className=" lg:block absolute top-70 right-10 -translate-y-1/2 -z-10 pointer-events-none">
        <div className="blob bg-[#DEC7FE] opacity-[60%] blur-2xl rounded-full w-[400px] h-[400px]"></div>
      </div>
       <div className=" lg:block absolute top-20 left-10 -translate-y-1/2 -z-10 pointer-events-none">
        <div className="blob5 bg-[#DEC7FE] opacity-[60%] blur-2xl rounded-full w-[400px] h-[400px]"></div>
      </div>
        
            <Navbar/>
        {children}
         
        <Footer />
         </>
      </body>
      
    </html>
    </>
  );
}
